version: 2.1

default_steps:
  - install_dependencies: &install_dependencies
      run:
        name: "Install dependencies"
        command: |
          pip3 install virtualenv
          virtualenv -p python3 venv
          source venv/bin/activate
          pip3 install -r requirements.dev.txt && pip3 install tensorflow==1.14.0

jobs:
  lint:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      # - restore_cache:
      #     key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - *install_dependencies
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "./venv"
      - run: flake8 kashgari

  test:
    docker:
      - image: circleci/python:3.7.5
    parallelism: 4
    steps:
      - checkout
      # - restore_cache:
      #     key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - *install_dependencies
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "./venv"
      - run:
          name: run tests
          no_output_timeout: 1800
          command: |
            TESTFILES=$(circleci tests glob "tests/**/*.py" | circleci tests split)
            echo $TESTFILES
            mkdir -pv test-reports
            pytest --doctest-modules --junitxml=test-reports/junit.xml --cov=kashgari --cov-report=xml --cov-report=html $TESTFILES
      - store_test_results:
          path: test-results

workflows:
  version: 2
  lint-workflow:
    jobs:
      - lint
      - test:
          requires:
            - lint
