version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: pip3 install virtualenv
      - run: virtualenv -p python3 venv
      - restore_cache: # ensure this step occurs *before* installing dependencies
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            source venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "./venv"
      - flake8 kashgari
