version: 2.1

default_steps:
  - install_dependencies: &install_dependencies
      run:
        name: "Install dependencies"
        command: |
          pip3 install virtualenv
          virtualenv -p python3 venv
          source venv/bin/activate
          pip3 install -r requirements.dev.txt && pip3 install tensorflow==1.14.0

  - default_restore_cache: &default_restore_cache
      restore_cache:
        key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}

  - default_save_cache: &default_save_cache
      save_cache:
        key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - "./venv"

jobs:
  lint:
    docker:
      - image: circleci/python:3.7.5
    resource_class: small
    steps:
      - checkout
      - *default_restore_cache
      - *install_dependencies
      - *default_save_cache
      - run:
          command: |
            source venv/bin/activate
            flake8 kashgari

  test:
    docker:
      - image: circleci/python:3.7.5
    resource_class: medium
    parallelism: 4
    steps:
      - checkout
      - *default_restore_cache
      - *install_dependencies
      - *default_save_cache
      - run:
          name: run tests
          no_output_timeout: 1800
          command: |
            source venv/bin/activate
            TESTFILES=$(circleci tests glob "tests/**/*.py" | circleci tests split)
            echo $TESTFILES
            mkdir -pv test-reports
            pytest --doctest-modules --junitxml=test-reports/junit.xml --cov=kashgari --cov-report=xml --cov-report=html $TESTFILES
      - store_test_results:
          path: test-reports

workflows:
  version: 2
  lint-workflow:
    jobs:
      - lint
      - test:
          requires:
            - lint
